Repository vegaprotocol/networks-internal, pull requests merged in 2023-01, with the labels that each got.

#220 chore: rename network param stakeToCcyVolume for Devnet 1
  devnet1/templates/genesis-template.json
Labels: no-issue

#226 feat: update siskas param for stagnet3
  stagnet3/templates/genesis-template.json
Labels: no-issue

#231 Change to asset proposal min participation
  sandbox/templates/genesis-template.json
Labels: no-issue

#232 chore: update vegawallet configs
  devnet1/vegawallet-devnet1.toml
  stagnet1/vegawallet-stagnet1.toml
  stagnet3/vegawallet-stagnet3.toml
Labels: no-issue, KTLO

#233 chore: redeploy smart contracts for Devnet 1
  devnet1/templates/genesis-template.json
  devnet1/templates/smart_contracts.json
Labels: KTLO
